CHROMIUM: net: xt_qtaguid: Remove unnecessary check for in_ifaddr.ifa_label != NULL
The checks are not necessary since in_ifaddr.ifa_label is character array,
not a pointer.

This fixes two clang warnings like this:

net/netfilter/xt_qtaguid.c:1078:11: error: address of array 'ifa->ifa_label'
will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]

BUG=chromium:702746
TEST=build with clang for edgar

Change-Id: Iff3cde672742c29e486f91239f668b8d12f3eda2
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/501528
Reviewed-by: Douglas Anderson <dianders@chromium.org>